# Generated by Django 3.2 on 2023-02-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230210_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='get_newsletter',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Get the newsletter'),
        ),
    ]
