# Generated by Django 3.2 on 2023-02-10 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='product/images/', verbose_name='Image 1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='product/images/', verbose_name='Image 2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='product/images/', verbose_name='Image 3')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='product/images/', verbose_name='Image 4')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Color')),
                ('material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Material')),
                ('price', models.BigIntegerField(default=0, verbose_name='Price')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_category', to='products.category', verbose_name='category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('warranty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_warranty', to='products.warranty', verbose_name='warranty')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_product', to='products.product', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
