# Generated by Django 3.2 on 2023-02-11 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='created_by',
        ),
        migrations.AddField(
            model_name='coupon',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.customuser', verbose_name='User'),
            preserve_default=False,
        ),
    ]
